import "./globals.css";
import { Michroma, Inter } from "next/font/google";
import Navbar from "./component/navbar";
import Footer from "./component/footer";
import SmoothScroll from "./component/smoothScroll";

const michroma = Michroma({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-michroma",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Skynetech",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${michroma.variable} ${inter.variable}`}>
            <SmoothScroll>
              <Navbar />
              {children}
              <Footer />
            </SmoothScroll>
      </body>
    </html>
  );
}
